services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: docker_laravel_db
      MYSQL_USER: docker_laravel
      MYSQL_PASSWORD: docker_laravel_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php/Dockerfile.prod
    volumes:
      - ./src:/var/www/html
    command: php-fpm
    ports: []  # 公開せずNginx経由に限定
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
