services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: docker_laravel_db
      MYSQL_USER: docker_laravel
      MYSQL_PASSWORD: docker_laravel_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  php:
    command: >
      sh -c "
      composer install --no-dev --optimize-autoloader &&
      php artisan config:cache &&
      php artisan migrate &&
      php-fpm"
    environment:
      APP_ENV: production
      APP_DEBUG: false
    volumes:
      - ./src:/var/www/html
      - ./php/php.prod.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:


