services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: docker_laravel_db
      MYSQL_USER: docker_laravel
      MYSQL_PASSWORD: docker_laravel_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: docker_laravel
      PMA_PASSWORD: docker_laravel_pass
    ports:
      - "13081:80"
    volumes:
      - phpmyadmin_data:/sessions
    networks:
      - laravel

  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173" # Vite開発用
      - "9012:9012"    # ← Xdebug 用ポートを追加
    command: bash -c "cd /var/www/html && npm install && npm run dev & php-fpm"
    networks:
      - laravel

  nginx:
    image: nginx:latest
    ports:
      - "13080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

volumes:
  db_data:
  phpmyadmin_data:

networks:
  laravel:
