FROM php:8.2-fpm

# 必要なシステムパッケージのみ（NodeやXdebugは不要）
RUN apt-get update && apt-get install -y \
    unzip curl zip git \
    libzip-dev libonig-dev libpng-dev \
    libxml2-dev libjpeg-dev libfreetype6-dev \
    libwebp-dev libgd-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-install pdo_mysql mbstring zip gd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Composerをインストール（グローバル）
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 作業ディレクトリ（Laravelのルート）
WORKDIR /var/www/html